name: Expo Web CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build Expo web (static export)
        run: npx expo export --platform web
        env:
          EXPO_PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.EXPO_PUBLIC_APPWRITE_ENDPOINT }}
          EXPO_PUBLIC_APPWRITE_PROJECT_ID: ${{ secrets.EXPO_PUBLIC_APPWRITE_PROJECT_ID }}
          EXPO_PUBLIC_APPWRITE_DATABASE_ID: ${{ secrets.EXPO_PUBLIC_APPWRITE_DATABASE_ID }}
          EXPO_PUBLIC_APPWRITE_USERS_COLLECTION_ID: ${{ secrets.EXPO_PUBLIC_APPWRITE_USERS_COLLECTION_ID }}

      - name: Upload web build (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: expo-web-dist
          path: dist
